/**
 * Centralized Access Areas Configuration
 * 
 * Categories:
 *   "public"             - Both students and staff can access
 *   "staff-only"         - Staff only (students denied, can request)
 *   "student-requestable"- Students can request (staff have default access)
 *   "restricted"         - Neither (both can request temp access)
 */

const ACCESS_AREAS = [
  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 1: Areas Accessible to Both Students and Staff (Public)
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "library",
    name: "University Library",
    category: "public",
    section: "General Access (All Users)",
    description: "Main university library with reading rooms, archives, and e-resource centres.",
    studentAccess: true,
    staffAccess: true,
  },
  {
    id: "cafeteria",
    name: "Cafeteria",
    category: "public",
    section: "General Access (All Users)",
    description: "University cafeteria and dining halls.",
    studentAccess: true,
    staffAccess: true,
  },
  {
    id: "medical-centre",
    name: "Medical Centre",
    category: "public",
    section: "General Access (All Users)",
    description: "University health services, clinic, and dispensary.",
    studentAccess: true,
    staffAccess: true,
  },
  {
    id: "student-affairs",
    name: "Student Affairs Office",
    category: "public",
    section: "General Access (All Users)",
    description: "Student support, counselling, and welfare services.",
    studentAccess: true,
    staffAccess: true,
  },

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 2: Areas Restricted to Students (Staff Only)
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "dept-admin-office",
    name: "Department Administrative Office",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Departmental administrative offices and faculty workspaces.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
  },
  {
    id: "registry-office",
    name: "Registry Office",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Academic records, admissions, and student registration office.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
  },
  {
    id: "bursary-office",
    name: "Bursary Office",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "University financial services, fee payments, and accounting.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
  },
  {
    id: "hr-office",
    name: "Human Resources Office",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Staff personnel records, recruitment, and HR services.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: false,
  },
  {
    id: "staff-meeting-room",
    name: "Staff Meeting Room",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Staff conference rooms and meeting chambers.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: false,
  },
  {
    id: "senate-building",
    name: "Senate Building Offices",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Senate building administrative offices and academic planning suites.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: false,
  },
  {
    id: "academic-planning",
    name: "Academic Planning Office",
    category: "staff-only",
    section: "Staff-Only Administrative Areas",
    description: "Curriculum development, academic calendar planning, and policy coordination.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: false,
  },

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 3: Highly Restricted Areas (Restricted to Both)
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "server-room",
    name: "Server Room",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Core university servers, databases, and network cabinets.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "network-ops",
    name: "Network Operations Centre",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Network monitoring, operations, and telecommunications hub.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "exam-strong-room",
    name: "Examination Strong Room",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Secure storage of examination materials and question papers.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "finance-archives",
    name: "Finance Records Archive",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "University financial records, audit trails, and historical archives.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "security-control-room",
    name: "Security Control Room",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Campus security monitoring, CCTV surveillance, and emergency coordination.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "data-centre",
    name: "Data Centre",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Primary data storage, backup systems, and disaster recovery infrastructure.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "vc-office",
    name: "Vice Chancellor's Office",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Office of the Vice Chancellor. Access by permission only.",
    studentAccess: false,
    staffAccess: false,
  },
  {
    id: "senate-chamber",
    name: "Senate Chamber",
    category: "restricted",
    section: "Highly Restricted Infrastructure",
    description: "Senate meeting chamber. Access requires special authorization.",
    studentAccess: false,
    staffAccess: false,
  },

  // ────────────────────────────────────────────────────────────────────────────
  // SECTION 4: Areas Students Can Request Access To
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: "staff-office",
    name: "Staff Office",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Individual staff offices for project supervision and consultations.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Project supervision",
  },
  {
    id: "dept-office",
    name: "Department Office",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Departmental office for course registration issues.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Course registration issues",
  },
  {
    id: "registry-request",
    name: "Registry Office (Student Request)",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Registry office for certificate collection and academic records.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Certificate collection",
  },
  {
    id: "bursary-request",
    name: "Bursary Office (Student Request)",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Bursary office for payment verification and fee inquiries.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Payment verification",
  },
  {
    id: "exam-office",
    name: "Examination Office",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Examination office for exam-related inquiries.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Exam-related inquiry",
  },
  {
    id: "ict-support",
    name: "ICT Support Centre",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "ICT support centre for student portal and account issues.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Student portal issues",
  },
  {
    id: "computer-lab",
    name: "Computer Laboratory",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Computer lab for after-hours practical work.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "After-hours practical work",
  },
  {
    id: "research-lab",
    name: "Research Laboratory",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Research lab for final-year projects and research work.",
    studentAccess: false,
    staffAccess: true,
    studentRequestable: true,
    requestReason: "Final-year project or research",
  },
  {
    id: "vc-office-request",
    name: "Vice Chancellor's Office",
    category: "student-requestable",
    section: "Requestable Areas (Students)",
    description: "Office of the Vice Chancellor. Requires special request.",
    studentAccess: false,
    staffAccess: false,
    studentRequestable: true,
    requestReason: "Special appointment",
  },
];

export default ACCESS_AREAS;